export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ITEM_REMOVE_FROM_CART = 'ITEM_REMOVE_FROM_CART';
export const SET_CART_DATA = 'SET_CART_DATA';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const DECREASE_ITEM_FROM_CART = 'DECREASE_ITEM_FROM_CART';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY'
;
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';