name: Build and Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t techmannih/ecommerce:v1 .
        docker push techmannih/ecommerce:v1

    - name: Deploy to Azure Container Instances
      run: |
        az container create \
          --resource-group frontend \
          --name myecommerce \
          --image techmannih/ecommerce:v1 \
          --cpu 1 --memory 1 \
          --registry-login-server index.docker.io \
          --registry-username ${{ secrets.DOCKER_USERNAME }} \
          --registry-password ${{ secrets.DOCKER_PASSWORD }} \
          --ports 80 \
          --ip-address public
